import Footer from "./Footer";
import Navbar from "./Navbar";
import Head from "next/head";

const Layout = ({ children }) => {
	return (
		<div className="scroll-smooth">
			<Head>
				<title>MJ Manilag</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			{children}
			<Footer />
		</div>
	);
};

export default Layout;
